// stubs/inertia-react/resources/js/Components/Tooltip/Tooltip.jsx


import { Floating } from "../Floating"

export const Tooltip = ({
                          animation = "duration-300",
                          arrow = true,
                          children,
                          className,
                          content,
                          placement = "top",
                          style = "dark",
                          theme: customTheme = {},
                          trigger = "hover",
                          ...props
                        }) => {
  const theme = mergeDeep(getTheme().tooltip, customTheme)

  return (
      <Floating
          animation={animation}
          arrow={arrow}
          content={content}
          placement={placement}
          style={style}
          theme={theme}
          trigger={trigger}
          className={className}
          {...props}
      >
        {children}
      </Floating>
  )
}

Tooltip.displayName = "Tooltip"

// stubs/inertia-vue/resources/js/Components/Tooltip/Tooltip.vue
<script setup>
import "floating-vue/dist/style.css"
import { computed } from "vue"
const props = withDefaults(defineProps(), {
    placement: "top",
    theme: "dark",
    trigger: "hover"
})
const theme = computed(() => {
    const themes = {
        light: "tooltip-light",
        dark: "tooltip-dark"
    }
    return themes[props.theme]
})

</script>
<template>
    <div class="flex items-start">
        <Tooltip :placement="placement" :triggers="[trigger]" :theme="theme" auto-hide>
            <slot name="trigger"></slot>
            <template #popper>
                <slot name="content"></slot>
            </template>
        </Tooltip>
    </div>
</template>
